In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('yq_dataframe.csv')

In [3]:
data.head(10)

,A_1,A_2,A_3,B_1,B_2,B_3,X_1,X_2,X_3,E_g,HTL,ETL,Voc(volts),Jsc,Max PCE,A,B,X
0,Cs/0.0625,MA/0.1875,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.045,20.7,14.3,Cs/MA/FA,Pb,I/Br
1,Cs/0.0625,MA/0.1875,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.021,20.9,12.4,Cs/MA/FA,Pb,I/Br
2,Cs/0.0525,MA/0.1975,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.054,20.4,15.9,Cs/MA/FA,Pb,I/Br
3,Cs/0.0525,MA/0.1975,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.022,20.7,15.2,Cs/MA/FA,Pb,I/Br
4,Cs/0.0375,MA/0.2125,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.050,20.9,16.0,Cs/MA/FA,Pb,I/Br
5,Cs/0.0375,MA/0.2125,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.060,21.1,16.8,Cs/MA/FA,Pb,I/Br
6,Cs/0.025,MA/0.225,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.076,21.0,14.9,Cs/MA/FA,Pb,I/Br
7,Cs/0.025,MA/0.225,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.049,20.7,16.3,Cs/MA/FA,Pb,I/Br
8,Cs/0.0125,MA/0.2375,FA/0.75,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,0.913,17.9,8.5,Cs/MA/FA,Pb,I/Br
9,Cs/0.0289,MA/0.1411,FA/0.83,Pb/1,NaN,NaN,I/0.83,Br/0.17,NaN,NaN,spiro-OMeTAD,TiO2,1.061,20.4,15.8,MA/FA,Pb,I/Br

In [4]:
data['Max PCE'].max()

20.800000000000001

In [5]:
data.sort_values('Max PCE', ascending=False)[:1].index

Int64Index([97], dtype='int64')

In [6]:
data.loc[97]

A_1                       FA/1
A_2                        NaN
A_3                        NaN
B_1                       Pb/1
B_2                        NaN
B_3                        NaN
X_1                    I/0.952
X_2                   Br/0.048
X_3                        NaN
E_g                        NaN
HTL               Spiro-OMeTAD
ETL            mesoporous TiO2
Voc(volts)                1.16
Jsc                       24.6
Max PCE                   20.8
A                           FA
B                           Pb
X                            I
Name: 97, dtype: object

In [7]:
data1 = pd.DataFrame()
# split the element and its ratio
data1['A1'], data1['A1_ratio'] = data['A_1'].str.split('/',1).str
data1['A2'], data1['A2_ratio'] = data['A_2'].str.split('/',1).str
data1['A3'], data1['A3_ratio'] = data['A_3'].str.split('/',1).str
data1['B1'], data1['B1_ratio'] = data['B_1'].str.split('/',1).str
data1['B2'], data1['B2_ratio'] = data['B_2'].str.split('/',1).str
data1['X1'], data1['X1_ratio'] = data['X_1'].str.split('/',1).str
data1['X2'], data1['X2_ratio'] = data['X_2'].str.split('/',1).str
data1['PCE'] = data['Max PCE']
data1['A'] = data['A'] 
data1['B'] = data['B']
data1['X'] = data['X']
data1 = data1.fillna(0)

In [8]:
data1 = data1.fillna(0)
data1.head(10)

,A1,A1_ratio,A2,A2_ratio,A3,A3_ratio,B1,B1_ratio,B2,B2_ratio,X1,X1_ratio,X2,X2_ratio,PCE,A,B,X
0,Cs,0.0625,MA,0.1875,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,14.3,Cs/MA/FA,Pb,I/Br
1,Cs,0.0625,MA,0.1875,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,12.4,Cs/MA/FA,Pb,I/Br
2,Cs,0.0525,MA,0.1975,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,15.9,Cs/MA/FA,Pb,I/Br
3,Cs,0.0525,MA,0.1975,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,15.2,Cs/MA/FA,Pb,I/Br
4,Cs,0.0375,MA,0.2125,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,16.0,Cs/MA/FA,Pb,I/Br
5,Cs,0.0375,MA,0.2125,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,16.8,Cs/MA/FA,Pb,I/Br
6,Cs,0.025,MA,0.225,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,14.9,Cs/MA/FA,Pb,I/Br
7,Cs,0.025,MA,0.225,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,16.3,Cs/MA/FA,Pb,I/Br
8,Cs,0.0125,MA,0.2375,FA,0.75,Pb,1,0,0,I,0.83,Br,0.17,8.5,Cs/MA/FA,Pb,I/Br
9,Cs,0.0289,MA,0.1411,FA,0.83,Pb,1,0,0,I,0.83,Br,0.17,15.8,MA/FA,Pb,I/Br

In [9]:
data1['A_sum'] = data1['A1_ratio'].astype(float) + data1['A2_ratio'].astype(float) + data1['A3_ratio'].astype(float)
data1['B_sum'] = data1['B1_ratio'].astype(float) + data1['B2_ratio'].astype(float)
data1['X_sum'] = data1['X1_ratio'].astype(float) + data1['X2_ratio'].astype(float)

In [10]:
data1.head(10)

,A1,A1_ratio,A2,A2_ratio,A3,A3_ratio,B1,B1_ratio,B2,B2_ratio,...,X1_ratio,X2,X2_ratio,PCE,A,B,X,A_sum,B_sum,X_sum
0,Cs,0.0625,MA,0.1875,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,14.3,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
1,Cs,0.0625,MA,0.1875,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,12.4,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
2,Cs,0.0525,MA,0.1975,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,15.9,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
3,Cs,0.0525,MA,0.1975,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,15.2,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
4,Cs,0.0375,MA,0.2125,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,16.0,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
5,Cs,0.0375,MA,0.2125,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,16.8,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
6,Cs,0.025,MA,0.225,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,14.9,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
7,Cs,0.025,MA,0.225,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,16.3,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
8,Cs,0.0125,MA,0.2375,FA,0.75,Pb,1,0,0,...,0.83,Br,0.17,8.5,Cs/MA/FA,Pb,I/Br,1.0,1.0,1.0
9,Cs,0.0289,MA,0.1411,FA,0.83,Pb,1,0,0,...,0.83,Br,0.17,15.8,MA/FA,Pb,I/Br,1.0,1.0,1.0

In [11]:
data1.loc[data1['A_sum']!=1]

,A1,A1_ratio,A2,A2_ratio,A3,A3_ratio,B1,B1_ratio,B2,B2_ratio,...,X1_ratio,X2,X2_ratio,PCE,A,B,X,A_sum,B_sum,X_sum
20,Al3+,0.075,MA,1.0,0,0,Pb,1,0,0,...,1.0,0,0,13.6,MA,Pb,I,1.0750,1.0,1.000
21,Al3+,0.15,MA,1.0,0,0,Pb,1,0,0,...,1.0,0,0,15.8,Al/MA,Pb,I,1.1500,1.0,1.000
22,Al3+,0.3,MA,1.0,0,0,Pb,1,0,0,...,1.0,0,0,14.2,Al/MA,Pb,I,1.3000,1.0,1.000
23,Al3+,0.75,MA,1.0,0,0,Pb,1,0,0,...,1.0,0,0,9.8,Al/MA,Pb,I,1.7500,1.0,1.000
24,Al3+,1.5,MA,1.0,0,0,Pb,1,0,0,...,1.0,0,0,5.5,Al/MA,Pb,I,2.5000,1.0,1.000
67,FA,0.81,MA,0.15,0,0,Pb,1.0,0,0,...,0.836,Br,0.15,16.1,FA/Cs,Pb,I/SCN,0.9600,1.0,0.986
68,FA,0.81,MA,0.15,0,0,Pb,1.0,0,0,...,0.836,Br,0.15,17.2,FA/MA,Pb,I/Br,0.9600,1.0,0.986
104,Al,0.00075,MA,0.99775,0,0,Pb,1,0,0,...,1,0,0,16.4,MA,Pb,I,0.9985,1.0,1.000
105,Al,0.0015,MA,0.9955,0,0,Pb,1,0,0,...,1,0,0,18.2,Al/MA,Pb,I,0.9970,1.0,1.000
106,Al,0.003,MA,0.991,0,0,Pb,1,0,0,...,1,0,0,16.6,Al/MA,Pb,I,0.9940,1.0,1.000
107,Al,0.0075,MA,0.9775,0,0,Pb,1,0,0,...,1,0,0,11.7,Al/MA,Pb,I,0.9850,1.0,1.000
108,Al,0.015,MA,0.955,0,0,Pb,1,0,0,...,1,0,0,6.7,Al/MA,Pb,I,0.9700,1.0,1.000

In [12]:
data1.loc[data1['B_sum']!=1]

Empty DataFrame
Columns: [A1, A1_ratio, A2, A2_ratio, A3, A3_ratio, B1, B1_ratio, B2, B2_ratio, X1, X1_ratio, X2, X2_ratio, PCE, A, B, X, A_sum, B_sum, X_sum]
Index: []

[0 rows x 21 columns]

In [13]:
data1.loc[data1['X_sum']!=1]

,A1,A1_ratio,A2,A2_ratio,A3,A3_ratio,B1,B1_ratio,B2,B2_ratio,...,X1_ratio,X2,X2_ratio,PCE,A,B,X,A_sum,B_sum,X_sum
36,MA,1.0,0,0,0,0,Pb,0.97,Sn,0.03,...,2.94,Br,0.06,5.24,MA/Cs,Pb,I,1.00,1.0,3.000
37,MA,1.0,0,0,0,0,PB,0.95,Sn,0.05,...,2.90,Br,0.10,7.59,MA,Pb/Sn,I/Br,1.00,1.0,3.000
38,MA,1.0,0,0,0,0,PB,0.90,Sn,0.10,...,2.80,Br,0.20,4.74,MA,Pb/Sn,I/Br,1.00,1.0,3.000
39,Ma,0.95,Cs,0.05,0,0,Pb,0.95,Sn,0.05,...,2.90,Br,0.10,8.25,MA,Pb/Sn,I/Br,1.00,1.0,3.000
40,MA,0.90,Cs,0.10,0,0,Pb,0.90,Sn,0.10,...,2.80,Br,0.20,6.50,MA/Cs,Pb/Sn,I/Br,1.00,1.0,3.000
41,Ma,0.95,Cs,0.05,0,0,Pb,0.95,Sn,0.05,...,2.85,Br,0.15,6.50,MA/Cs,Pb/Sn,I/Br,1.00,1.0,3.000
42,MA,0.90,Cs,0.10,0,0,Pb,0.90,Sn,0.10,...,2.70,Br,0.30,5.94,MA/Cs,Pb/Sn,I/Br,1.00,1.0,3.000
67,FA,0.81,MA,0.15,0,0,Pb,1.0,0,0,...,0.836,Br,0.15,16.10,FA/Cs,Pb,I/SCN,0.96,1.0,0.986
68,FA,0.81,MA,0.15,0,0,Pb,1.0,0,0,...,0.836,Br,0.15,17.20,FA/MA,Pb,I/Br,0.96,1.0,0.986
81,MA,1,0,0,0,0,Pb,0.97,Sb,0.03,...,0.98,Br,0.03,6.47,MA,Pb,I,1.00,1.0,1.010

In [11]:
# load the dataframe with assigned ratio on A, B, and X site
df = pd.read_csv('Ratio_dataframe.csv')

In [12]:
# use the ratio of first compound to represent the pair
# for instance MA/FA = 0.17 means MA/FA = 0.17/0.83
# the total ratio of each pair for A, B, and X sites should all equal to 1
df.head()

,MA/FA,MA,Al/MA,FA/Cs,MA/Cs,FA,MA/HA,FA/Rb,Cs,MA/Ag,...,Pb/Sr,Pb/Zn,Sn,Ge,I/Br,I,I/SCN,I/Cl,Br,PCE
0,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.83,NaN,NaN,NaN,NaN,13.4
1,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.83,NaN,NaN,NaN,NaN,12.9
2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,13.2
3,NaN,NaN,0.075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,13.6
4,NaN,NaN,0.150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,15.8

In [13]:
# replace NA with 0
df1 = df.fillna(0)
df1.head()

,MA/FA,MA,Al/MA,FA/Cs,MA/Cs,FA,MA/HA,FA/Rb,Cs,MA/Ag,...,Pb/Sr,Pb/Zn,Sn,Ge,I/Br,I,I/SCN,I/Cl,Br,PCE
0,0.17,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.83,0.0,0.0,0.0,0.0,13.4
1,0.17,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.83,0.0,0.0,0.0,0.0,12.9
2,0.00,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,13.2
3,0.00,0.0,0.075,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,13.6
4,0.00,0.0,0.150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0,15.8

In [14]:
df1.loc[1]

MA/FA     0.17
MA        0.00
Al/MA     0.00
FA/Cs     0.00
MA/Cs     0.00
FA        0.00
MA/HA     0.00
FA/Rb     0.00
Cs        0.00
MA/Ag     0.00
Pb        1.00
Pb/Sn     0.00
Pb/Sb     0.00
Pb/Co     0.00
Pb/Cu     0.00
Pb/Fe     0.00
Pb/Mg     0.00
Pb/Mn     0.00
Pb/Ni     0.00
Pb/Sr     0.00
Pb/Zn     0.00
Sn        0.00
Ge        0.00
I/Br      0.83
I         0.00
I/SCN     0.00
I/Cl      0.00
Br        0.00
PCE      12.90
Name: 1, dtype: float64

In [19]:
# replce all non-zero values to 1 except last 'PCE' column
df2 = df1.drop('PCE', axis=1)
df2[df2 != 0] = 1
df2.head()

,MA/FA,MA,Al/MA,FA/Cs,MA/Cs,FA,MA/HA,FA/Rb,Cs,MA/Ag,...,Pb/Ni,Pb/Sr,Pb/Zn,Sn,Ge,I/Br,I,I/SCN,I/Cl,Br
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [20]:
df2['PCE'] = df1.PCE
df2.head()

,MA/FA,MA,Al/MA,FA/Cs,MA/Cs,FA,MA/HA,FA/Rb,Cs,MA/Ag,...,Pb/Sr,Pb/Zn,Sn,Ge,I/Br,I,I/SCN,I/Cl,Br,PCE
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13.4
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,12.9
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,13.2
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,13.6
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,15.8

In [21]:
df2.loc[1]

MA/FA     1.0
MA        0.0
Al/MA     0.0
FA/Cs     0.0
MA/Cs     0.0
FA        0.0
MA/HA     0.0
FA/Rb     0.0
Cs        0.0
MA/Ag     0.0
Pb        1.0
Pb/Sn     0.0
Pb/Sb     0.0
Pb/Co     0.0
Pb/Cu     0.0
Pb/Fe     0.0
Pb/Mg     0.0
Pb/Mn     0.0
Pb/Ni     0.0
Pb/Sr     0.0
Pb/Zn     0.0
Sn        0.0
Ge        0.0
I/Br      1.0
I         0.0
I/SCN     0.0
I/Cl      0.0
Br        0.0
PCE      12.9
Name: 1, dtype: float64